[project]
name = "svgmapviewer"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "svgmapviewer-tools-floors",
    "types-lxml>=2026.1.1",
]

[tool.uv.sources]
svgmapviewer-tools-floors = { path = "packages/tools-floors" }
