[project]
name = "svgmapviewer-tools-floors"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
  "cssselect>=1.3.0",
  "lxml>=6.0.2",
  "lxml-stubs>=0.5.1",
  "numpy>=2.4.1",
  "pyparsing>=3.3.2",
  "pytest>=9.0.2",
  "requests>=2.32.5",
  "scribus>=0.1.3",
  "tinycss2>=1.5.1",
  "zstandard>=0.25.0",
]

[tool.ruff]
exclude = ["inkex"]
